### ISSUE TITLE
File is not being written

### ISSUE THREAD

**Issue by YogeshDornala** [devops-actions/json-to-file#60]
Hello,
I am trying to write a sample file to a local branch.
The run is successful but the file does not get create in the local branch. Am I missing something?
![image](https://user-images.githubusercontent.com/101328112/179906445-36625c2f-b082-4067-97f0-fcacb50e6ab1.png)

![image](https://user-images.githubusercontent.com/101328112/179906235-ec332920-02c8-4798-a879-a70c16947029.png)

**Comment by yasamoka** [comment]
Just faced the same issue. The path is taken as relative to `${{ github.workspace }}`. Provide an absolute path and it should work.
